
spring:
  #数据源和jpa配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    #数据库相关的配置url  -SSL连接设置为false
    url: jdbc:mysql://localhost:3306/seckilldb?characterEncoding=utf8&useSSL=false
    #配置用户名
    username: root
    #配置密码
    password: root
    hikari:
      ## 最小空闲连接数量
      minimumidle: 5
      ## 空闲连接存活最大时间，默认600000（10分钟）
      idleTimeout: 180000
      ## 连接池最大连接数，默认是10
      maximum-pool-size: 10
      ## 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      pool-name: Seckill-HikariCP
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis端口
    port: 6379
    # Redis密码默认为空
    password:
    # Redis连接超时时间
    timeout: 3000
server:
  port: 8089